-- Convertly production foundation for Supabase
-- Admin email requested by the owner: gamerzneel01@gmail.com
-- Run this whole file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

do $$ begin
  create type public.user_role as enum ('user','admin');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.subscription_status as enum ('trialing','active','past_due','canceled','expired');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.conversion_status as enum ('queued','processing','completed','failed','expired','canceled');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  display_name text,
  role public.user_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null default 'safepay',
  provider_customer_id text,
  provider_subscription_id text unique,
  plan text not null default 'pro_monthly',
  status public.subscription_status not null default 'trialing',
  current_period_start timestamptz,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete set null,
  source text not null default 'youtube',
  source_url text not null,
  quality integer not null check (quality between 144 and 2160),
  format text not null default 'mp4',
  status public.conversion_status not null default 'queued',
  progress integer not null default 0 check (progress between 0 and 100),
  job_id text,
  output_path text,
  download_expires_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists conversions_user_created_idx on public.conversions(user_id, created_at desc);
create index if not exists conversions_status_created_idx on public.conversions(status, created_at);

create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid not null references public.profiles(id) on delete cascade,
  referred_user_id uuid references public.profiles(id) on delete set null,
  referral_code text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique(referrer_id, referred_user_id)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists analytics_event_created_idx on public.analytics_events(event_name, created_at desc);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists subscriptions_updated_at on public.subscriptions;
create trigger subscriptions_updated_at before update on public.subscriptions
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, role)
  values (
    new.id,
    lower(new.email),
    coalesce(new.raw_user_meta_data->>'full_name', split_part(coalesce(new.email,''),'@',1)),
    case when lower(coalesce(new.email,'')) = 'gamerzneel01@gmail.com' then 'admin'::public.user_role else 'user'::public.user_role end
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Make the requested admin email admin even if the user already existed before the trigger was installed.
update public.profiles set role='admin', updated_at=now()
where lower(email)='gamerzneel01@gmail.com';

create or replace function public.is_admin(target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where id=target_user_id and role='admin');
$$;

create or replace function public.has_pro_access(target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin(target_user_id) or exists (
    select 1 from public.subscriptions s
    where s.user_id=target_user_id
      and s.status in ('trialing','active')
      and (s.current_period_end is null or s.current_period_end > now())
  );
$$;

grant execute on function public.is_admin(uuid) to authenticated;
grant execute on function public.has_pro_access(uuid) to authenticated;

-- Backfill users that existed before this trigger/schema was installed.
insert into public.profiles (id, email, display_name, role)
select
  u.id,
  lower(u.email),
  coalesce(u.raw_user_meta_data->>'full_name', split_part(coalesce(u.email,''),'@',1)),
  case when lower(coalesce(u.email,''))='gamerzneel01@gmail.com' then 'admin'::public.user_role else 'user'::public.user_role end
from auth.users u
where u.email is not null
on conflict (id) do update set
  email=excluded.email,
  display_name=excluded.display_name,
  role=case when lower(excluded.email)='gamerzneel01@gmail.com' then 'admin'::public.user_role else public.profiles.role end,
  updated_at=now();

alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.conversions enable row level security;
alter table public.referrals enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin on public.profiles for select to authenticated
using (id=auth.uid() or public.is_admin());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated
using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists subscriptions_select_self_or_admin on public.subscriptions;
create policy subscriptions_select_self_or_admin on public.subscriptions for select to authenticated
using (user_id=auth.uid() or public.is_admin());

drop policy if exists conversions_select_self_or_admin on public.conversions;
create policy conversions_select_self_or_admin on public.conversions for select to authenticated
using (user_id=auth.uid() or public.is_admin());

drop policy if exists conversions_insert_self on public.conversions;
create policy conversions_insert_self on public.conversions for insert to authenticated
with check (user_id=auth.uid());

drop policy if exists conversions_update_self_or_admin on public.conversions;
create policy conversions_update_self_or_admin on public.conversions for update to authenticated
using (user_id=auth.uid() or public.is_admin())
with check (user_id=auth.uid() or public.is_admin());

drop policy if exists referrals_select_self_or_admin on public.referrals;
create policy referrals_select_self_or_admin on public.referrals for select to authenticated
using (referrer_id=auth.uid() or referred_user_id=auth.uid() or public.is_admin());

drop policy if exists referrals_insert_self on public.referrals;
create policy referrals_insert_self on public.referrals for insert to authenticated
with check (referrer_id=auth.uid());

drop policy if exists analytics_insert_authenticated on public.analytics_events;
create policy analytics_insert_authenticated on public.analytics_events for insert to authenticated
with check (user_id=auth.uid());

drop policy if exists analytics_select_self_or_admin on public.analytics_events;
create policy analytics_select_self_or_admin on public.analytics_events for select to authenticated
using (user_id=auth.uid() or public.is_admin());

-- Admin can manage subscription/conversion records when authenticated as admin.
drop policy if exists subscriptions_admin_all on public.subscriptions;
create policy subscriptions_admin_all on public.subscriptions for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists conversions_admin_all on public.conversions;
create policy conversions_admin_all on public.conversions for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists profiles_admin_all on public.profiles;
create policy profiles_admin_all on public.profiles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Keep the public API surface narrow. Service-role backend can bypass RLS for trusted webhook/worker operations.

-- Converted MP4/MP3 files are stored in a private Supabase Storage bucket.
-- The service-role backend creates short-lived signed download URLs.
insert into storage.buckets (id, name, public)
values ('convertly-files', 'convertly-files', false)
on conflict (id) do update set public = false;

create index if not exists analytics_event_user_created_idx on public.analytics_events(user_id, created_at desc);
create index if not exists analytics_event_name_created_idx on public.analytics_events(event_name, created_at desc);


-- Step 14: Pro credits / advanced usage billing foundation.
-- This is an internal credit ledger; connect your real payment provider before selling credit packs.
create table if not exists public.credit_accounts (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance integer not null default 0 check (balance >= 0),
  monthly_allowance integer not null default 600 check (monthly_allowance >= 0),
  period_start timestamptz not null default date_trunc('month', now()),
  period_end timestamptz not null default (date_trunc('month', now()) + interval '1 month'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null,
  kind text not null check (kind in ('grant','monthly_reset','debit','refund')),
  reference_id text unique,
  reason text,
  created_at timestamptz not null default now()
);
create index if not exists credit_ledger_user_created_idx on public.credit_ledger(user_id, created_at desc);

alter table public.credit_accounts enable row level security;
alter table public.credit_ledger enable row level security;

drop policy if exists credit_accounts_select_self_or_admin on public.credit_accounts;
create policy credit_accounts_select_self_or_admin on public.credit_accounts for select to authenticated
using (user_id=auth.uid() or public.is_admin());

drop policy if exists credit_ledger_select_self_or_admin on public.credit_ledger;
create policy credit_ledger_select_self_or_admin on public.credit_ledger for select to authenticated
using (user_id=auth.uid() or public.is_admin());

drop trigger if exists credit_accounts_updated_at on public.credit_accounts;
create trigger credit_accounts_updated_at before update on public.credit_accounts
for each row execute function public.set_updated_at();

create or replace function public.ensure_credit_account(target_user_id uuid)
returns public.credit_accounts
language plpgsql
security definer
set search_path = public
as $$
declare row public.credit_accounts;
begin
  insert into public.credit_accounts(user_id, balance, monthly_allowance)
  values(target_user_id, 600, 600)
  on conflict (user_id) do nothing;
  select * into row from public.credit_accounts where user_id=target_user_id;
  if row.period_end <= now() then
    update public.credit_accounts set balance=monthly_allowance, period_start=date_trunc('month', now()), period_end=date_trunc('month', now()) + interval '1 month' where user_id=target_user_id returning * into row;
    insert into public.credit_ledger(user_id, amount, kind, reference_id, reason)
    values(target_user_id, row.monthly_allowance, 'monthly_reset', 'monthly-reset-'||to_char(now(),'YYYY-MM'), 'Monthly Pro credit reset')
    on conflict (reference_id) do nothing;
  end if;
  return row;
end;
$$;

grant execute on function public.ensure_credit_account(uuid) to service_role;

create or replace function public.get_credit_status(target_user_id uuid)
returns table(balance integer, monthly_allowance integer, reset_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare row public.credit_accounts;
begin
  select * into row from public.ensure_credit_account(target_user_id);
  return query select row.balance, row.monthly_allowance, row.period_end;
end;
$$;
grant execute on function public.get_credit_status(uuid) to service_role;

create or replace function public.consume_credits(target_user_id uuid, credit_amount integer, reference_id text)
returns table(ok boolean, balance integer, code text, message text)
language plpgsql
security definer
set search_path = public
as $$
declare current_balance integer;
begin
  if credit_amount <= 0 then return query select true, 0, 'NOOP', 'No credits required.'; return; end if;
  perform public.ensure_credit_account(target_user_id);
  if exists(select 1 from public.credit_ledger where credit_ledger.reference_id=consume_credits.reference_id and kind='debit') then
    select balance into current_balance from public.credit_accounts where user_id=target_user_id;
    return query select true, current_balance, 'ALREADY_DEBITED', 'Credits already reserved.'; return;
  end if;
  update public.credit_accounts set balance=balance-credit_amount where user_id=target_user_id and balance >= credit_amount returning balance into current_balance;
  if current_balance is null then
    select balance into current_balance from public.credit_accounts where user_id=target_user_id;
    return query select false, coalesce(current_balance,0), 'INSUFFICIENT_CREDITS', 'Not enough credits.'; return;
  end if;
  insert into public.credit_ledger(user_id, amount, kind, reference_id, reason) values(target_user_id, -credit_amount, 'debit', reference_id, 'Conversion credit reservation');
  return query select true, current_balance, 'OK', 'Credits reserved.';
end;
$$;
grant execute on function public.consume_credits(uuid,integer,text) to service_role;

create or replace function public.refund_credits(target_user_id uuid, credit_amount integer, reference_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare new_balance integer;
begin
  if credit_amount <= 0 then return true; end if;
  if exists(select 1 from public.credit_ledger where credit_ledger.reference_id='refund-'||refund_credits.reference_id) then return true; end if;
  update public.credit_accounts set balance=balance+credit_amount where user_id=target_user_id returning balance into new_balance;
  if new_balance is null then return false; end if;
  insert into public.credit_ledger(user_id, amount, kind, reference_id, reason) values(target_user_id, credit_amount, 'refund', 'refund-'||reference_id, 'Conversion failed or cancelled');
  return true;
end;
$$;
grant execute on function public.refund_credits(uuid,integer,text) to service_role;

create or replace function public.grant_credits(target_user_id uuid, credit_amount integer, reason text default 'Admin credit grant')
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  if credit_amount <= 0 then raise exception 'Credit amount must be positive'; end if;
  perform public.ensure_credit_account(target_user_id);
  update public.credit_accounts set balance=balance+credit_amount where user_id=target_user_id;
  insert into public.credit_ledger(user_id, amount, kind, reference_id, reason) values(target_user_id, credit_amount, 'grant', 'grant-'||gen_random_uuid()::text, reason);
  return 'granted';
end;
$$;
grant execute on function public.grant_credits(uuid,integer,text) to service_role;
